require("nvim-treesitter.install").prefer_git = false
return {
  ensure_installed = {
    -- 11 most popular languages
    "c_sharp",
    "css",
    "go",
    "html",
    "java",
    "javascript",
    "perl",
    "python",
    "rust",
    "scss",
    "sql",
    -- user parsers
    "bash",
    "cmake",
    "comment",
    "cpp",
    "dockerfile",
    "dot",
    "hcl",
    "hjson",
    "json",
    "json5",
    "jsonc",
    "latex",
    "make",
    "markdown",
    "query",
    "terraform",
    "toml",
    "typescript",
    "yaml",
  },
}
