vim.api.nvim_create_augroup("user", { clear = true })
vim.api.nvim_create_autocmd("BufNewFile,BufRead", {
  group = "user",
  pattern = "*.dbout",
  desc = "*.dbout generated by vim-dadbod is usually pgsql.",
  command = "let b:sql_type_override='pgsql' | set syntax=sql | set filetype=sql",
})
