return {
  {
    "tpope/vim-dadbod",
    config = function()
      vim.api.nvim_create_autocmd("BufNewFile,BufRead", {
        group = vim.api.nvim_create_augroup("User_DboutFile", { clear = true }),
        pattern = "*.dbout",
        desc = "*.dbout generated by vim-dadbod is usually pgsql.",
        command = "let b:sql_type_override='pgsql' | setfiletype sql",
      })
      vim.api.nvim_create_autocmd("FileType", {
        group = vim.api.nvim_create_augroup("User_SqlFiletype", { clear = true }),
        pattern = "sql",
        desc = "dadbod mappings in sql files",
        callback = function(data)
          -- <Cmd> does not work, as :DB command requires [range],
          -- and <Cmd> does not provide range by default (as : does via '<,'>).
          -- '<,'> can't be used with <Cmd>, as Command mode is not entered, and
          -- markers are not updated. Using line("v") and line(".") is too much
          -- hassle to go through.
          vim.keymap.set("v", "<Leader>bb", ":DB<CR>", { desc = "Execute the database query", buffer = data.buf })
        end,
      })
      vim.g.db = os.getenv "UPROAD_PROD_REDSHIFT_DSN"
    end,
    ft = "sql",
  },
}
