local treesitter = {
  ensure_installed = {
    "bash",
    "c",
    "cmake",
    "cpp",
    "css",
    "cuda",
    "dockerfile",
    "dot",
    "gitattributes",
    -- currently does not work - https://github.com/nvim-treesitter/nvim-treesitter/issues/3316
    -- "gitignore",
    "go",
    "graphql",
    "hcl",
    "html",
    "http",
    "java",
    "javascript",
    "json",
    "llvm",
    "lua",
    "markdown",
    "python",
    "query",
    "rust",
    "sql",
    "toml",
    "vim",
    "yaml",
  },
}

return treesitter
